// UI
export const SET_TAB_INDEX = 'SET_TAB_INDEX';
export const GET_THEME = 'GET_THEME';
export const SET_THEME = 'SET_THEME';

// Data
export const GET_DATA = 'GET_DATA';

// Resources
export const SORT_RESOURCE_USAGE = 'SORT_RESOURCE_USAGE';

// Dupes
export const SET_DUPES_TOTAL_QUANTITY = 'SET_DUPES_TOTAL_QUANTITY';
export const SET_DUPE_TRAIT_QUANTITY = 'SET_DUPE_TRAIT_QUANTITY';
export const SET_DUPE_WASTE = 'SET_DUPE_WASTE';

// Buildings
export const SET_BUILDINGS_LAYOUT = 'SET_BUILDINGS_LAYOUT';
export const SORT_BUILDINGS = 'SORT_BUILDINGS';
export const SET_BUILDING_QUANTITY = 'SET_BUILDING_QUANTITY';
export const SET_BUILDING_UTILIZATION = 'SET_BUILDING_UTILIZATION';
export const CLEAR_BUILDING_QUANTITIES = 'CLEAR_BUILDING_QUANTITIES';

// Food
export const SET_FOOD_QUANTITY = 'SET_FOOD_QUANTITY';

// Geysers
export const SET_GEYSER_VALUES = 'SET_GEYSER_VALUES';
export const ADD_GEYSER = 'ADD_GEYSER';
export const DELETE_GEYSER = 'DELETE_GEYSER';
