export const GET_DATA = "GET_DATA";

export const SORT_RESOURCE_USAGE = "SORT_RESOURCE_USAGE";

export const SET_BUILDINGS_LAYOUT = "SET_BUILDINGS_LAYOUT";
export const SORT_BUILDINGS = "SORT_BUILDINGS";
export const SET_BUILDING_QUANTITY = "SET_BUILDING_QUANTITY";
export const SET_BUILDING_UTILIZATION = "SET_BUILDING_UTILIZATION";
export const CLEAR_BUILDING_QUANTITIES = "CLEAR_BUILDING_QUANTITIES";

export const GET_THEME = "GET_THEME";
export const SET_THEME = "SET_THEME";

export const SAVE_QUANTITIES = "SAVE_QUANTITIES";
export const GET_QUANTITIES = "GET_QUANTITIES";