const INITIAL_STATE = {
  tabIndex: 0,
  collapseBuildingPanels: false,
  collapseBuildingPanelsTrigger: false,
  buildings: [],
  buildingsLayout: 'grid',
  buildingsOrderBy: '',
  buildingOrder: 'desc',
  resources: [],
  resourcesOrderBy: 'name',
  resourcesOrder: 'asc',
  theme: {},
  powerUsage: {},
  powerGeneration: {},
  powerCapacity: {},
  resourcesCapacity: {},
  dupes: {},
  food: [],
  geysers: {},
};